AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub Metrics - Simple RDS Database'

Resources:
  # Database Subnet Group
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for GitHub Metrics database
      SubnetIds:
        - subnet-00b847f7b0b5d9ee8
        - subnet-09e6c60058b176304
      Tags:
        - Key: Name
          Value: github-metrics-db-subnet-group

  # Database Security Group
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for GitHub Metrics database
      VpcId: vpc-0ba2ab356009cd2c7
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0  # Allow from anywhere for now (can restrict later)
      Tags:
        - Key: Name
          Value: github-metrics-db-sg

  # RDS Database
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: github-metrics-db
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: '17.5'
      MasterUsername: postgres
      MasterUserPassword: GitHubMetrics2025!
      AllocatedStorage: 20
      StorageType: gp2
      DBName: github_metrics
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      BackupRetentionPeriod: 1
      MultiAZ: false
      StorageEncrypted: false  # Simplified for free tier
      DeletionProtection: false
      PubliclyAccessible: true  # For easier access during development
      Tags:
        - Key: Name
          Value: github-metrics-database

Outputs:
  DatabaseEndpoint:
    Description: RDS database endpoint
    Value: !GetAtt Database.Endpoint.Address
    Export:
      Name: DatabaseEndpoint

  DatabaseConnectionString:
    Description: Database connection string
    Value: !Sub 'postgresql://postgres:GitHubMetrics2025!@${Database.Endpoint.Address}:5432/github_metrics'
    Export:
      Name: DatabaseConnectionString
